# Use Node 20
FROM node:20-bullseye

# Set working directory
WORKDIR /app

# Copy package.json & tsconfig
COPY package*.json tsconfig.json ./

# Install dependencies
RUN npm install --production

# Copy source files
COPY . .

# Compile TypeScript to JS
RUN npm run build

# Expose the port
EXPOSE 3000

# Run compiled JS
CMD ["npm", "start"]
